"""empty message

Revision ID: 53900d8e18c7
Revises: 80efb0b5ef74
Create Date: 2020-11-02 18:25:09.395108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53900d8e18c7'
down_revision = '80efb0b5ef74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'name')
    # ### end Alembic commands ###
